Upate custom cfme fact to allow the collection of other custom facts all under the 'cfme' name
RedHatOfficial/ansible-redhat_cloudforms pull request #9
Opened 2018-03-07 21:33 UTC by itewk

2018-03-07 21:36 UTC, curt-matthews requested changes
I don't see where the README has been updated.

2018-03-08 00:25 UTC, itewk commented
@curt-matthews i assumed you were updating that as another pull request since you hadn't dont it with your first one :)

2018-03-08 03:31 UTC, itewk commented
tested with a 5.8.1 to 5.8.2 upgrade

2018-03-08 04:57 UTC, curt-matthews approved these changes

2018-03-08 04:57 UTC, merged